language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email: false
branches:
  only:
  - master
env:
  global:
  - secure: adOG5j1pz/CPRGesvhRwX1Xfr5gs2rQSR4tbECR0ryDxD8QSrP74E7m7y8szLqu5I81K13JGS8DrrhLbwu+euR06QoRUj4J3l9z3JdylAp1oXQP8snnK7Rzqx0xyXCKXR4nf+HwkXzYbubZ749Age+m99iCldFZa7+VkF+Hhn72E9GsMnkLTQKTXsi6IAEzkGd8N+10mBqAC4qcdDOXX5kU/hDY6KGMEeBmg89orOz4JAzo3/6FsyHdukdRKawsWaqlYUaksCSuZnuPoZNvkubWW4woc6u62Nnw0EuCC1yFzWW5EnwfCH84uMyiXTc/OSwLi7RT1lpF++cAuNQjC33hJLV3as0rZnDfx0RYjqlvocJVZtAgrEDVv6N10Z8kZjharcn93wxMnFs7miB5rRZA67AAy4U9xG8pdckWHqpCwJqR/C15GTHVLVGUGWs7Pglr8f0QtInZ17RqFLDujl7/WVeFlF/dCWkbv8F+XtBh8PAnqys82+Vs6gzKudzoj75aj5Bib5cyMDa4artiOFqKp7TyPE0sa/L9X9904gxMsW4+YYSrRob+Q7JzPahYTS9gnN/xPlu5i29gbvPzHYuTtEZ9KsWpf29CWuLGy22KoPQkSTPuwxBSoYHXYmtwVrt8EYBUYcvQe+B6b73Qp/qU+mvFvBBKokOSIHGNEJ+s=
before_install:
- export BUILD_NAME=spring-microservice-samples-$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh build/build-services.sh
- sh build/build-docker.sh
after_success:
- sh build/tag-github.sh